# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QPushButton


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 529)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ghoGAFyesr-AShrxAAAuJUB7mKo138.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 511, 511))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        count = 0
        for i in range(0, 10):
            for j in range(0, 10):
                count += 1
                pqbutton = QtWidgets.QPushButton(self.groupBox)
                pqbutton.setGeometry(QtCore.QRect(10 + (50 * i), 10 + (50 * j), 41, 41))
                font = QtGui.QFont()
                font.setPointSize(20)
                pqbutton.setFont(font)
                pqbutton.setText("")
                pqbutton.setObjectName(f'pushButton_{count}')
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Крестики нолики"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
